src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nomCategorie = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $user_create;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $user_update;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $user_delete;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_create;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_update;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private $date_delete;
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nomCategorie;
    }

    public function setNomCategorie(?string $nomCategorie): static
    {
        $this->nomCategorie = $nomCategorie;
        return $this;
    }

    public function getUserCreate(): ?string
    {
        return $this->user_create;
    }

    public function setUserCreate(?string $user_create): static
    {
        $this->user_create = $user_create;

        return $this;
    }

    public function getUserUpdate(): ?string
    {
        return $this->user_update;
    }

    public function setUserUpdate(?string $user_update): static
    {
        $this->user_update = $user_update;

        return $this;
    }

    public function getUserDelete(): ?string
    {
        return $this->user_delete;
    }

    public function setUserDelete(?string $user_delete): static
    {
        $this->user_delete = $user_delete;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(?\DateTimeInterface $date_create): static
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(?\DateTimeInterface $date_update): static
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getDateDelete(): ?\DateTimeInterface
    {
        return $this->date_delete;
    }

    public function setDateDelete(?\DateTimeInterface $date_delete): static
    {
        $this->date_delete = $date_delete;

        return $this;
    }

}

src/Form/CategorieType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategorieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomCategorie')
            // ->add('user_create')
            // ->add('user_update')
            // ->add('user_delete')
            // ->add('date_create', null, [
            //     'widget' => 'single_text',
            // ])
            // ->add('date_update', null, [
            //     'widget' => 'single_text',
            // ])
            // ->add('date_delete', null, [
            //     'widget' => 'single_text',
            // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Categorie::class,
        ]);
    }
}

src/Controller/CategorieController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Form\CategorieType;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/categorie')]
class CategorieController extends AbstractController
{
    #[Route('/', name: 'app_categorie_index', methods: ['GET'])]
    public function index(CategorieRepository $categorieRepository): Response
    {
        return $this->render('categorie/index.html.twig', [
            'categories' => $categorieRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_categorie_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $categorie = new Categorie();
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($categorie);
            $entityManager->flush();

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/new.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_show', methods: ['GET'])]
    public function show(Categorie $categorie): Response
    {
        return $this->render('categorie/show.html.twig', [
            'categorie' => $categorie,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_categorie_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CategorieType::class, $categorie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('categorie/edit.html.twig', [
            'categorie' => $categorie,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_categorie_delete', methods: ['POST'])]
    public function delete(Request $request, Categorie $categorie, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$categorie->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($categorie);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_categorie_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/categorie/_delete_form.html.twig
<form method="post" action="{{ path('app_categorie_delete', {'id': categorie.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ categorie.id) }}">
    <button class="list-button">Supprimer</button>
</form>

templates/categorie/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="list-button">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

<style>
    
    .list-button {
        color: var(--black);
	    padding: 10px 15px;
	    border: none;
	    border-radius: 8px;
	    cursor: pointer;
	    font-weight: 600;
	    align-items: center;
	    grid-gap: 10px;
	    margin-top: 25px;
        margin-bottom: 15px;
	    transition: background-color 0.3s ease;
    }

    .list-button:hover {
        background-color:  #f5f5f5;
    }
</style>

templates/categorie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Categorie{% endblock %}

{% block css %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <h1>Nouvelle Categorie</h1>

    {{ include('categorie/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_categorie_index') }}">Afficher la Liste</a>

    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}

templates/categorie/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Catégorie{% endblock %}

{% block body %}
    <h1>Liste Catégorie</h1>

    <table class="table">
        <thead>
            <tr>
                {#<th>Id</th>#}
                <th>Nom Categorie</th>
                {# <th>User_create</th>
                <th>User_update</th>
                <th>User_delete</th>
                <th>Date_create</th>
                <th>Date_update</th>
                <th>Date_delete</th> #}
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for categorie in categories %}
            <tr>
                {# <td>{{ categorie.id }}</td> #}
                <td>{{ categorie.nomCategorie }}</td>
                {# <td>{{ categorie.userCreate }}</td>
                <td>{{ categorie.userUpdate }}</td>
                <td>{{ categorie.userDelete }}</td>
                <td>{{ categorie.dateCreate ? categorie.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ categorie.dateUpdate ? categorie.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ categorie.dateDelete ? categorie.dateDelete|date('Y-m-d H:i:s') : '' }}</td> #}
                <td>
                    <a href="{{ path('app_categorie_show', {'id': categorie.id}) }}">Afficher</a>
                    <a href="{{ path('app_categorie_edit', {'id': categorie.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_categorie_new') }}">Créer Nouvelle Catégorie</a>
{% endblock %}

templates/categorie/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Catégorie{% endblock %}

{% block body %}
    <h1>Créer Nouvelle Catégorie</h1>

    {{ include('categorie/_form.html.twig') }}

    <a href="{{ path('app_categorie_index') }}" class="link-btn">Afficher la Liste</a>
{% endblock %}

templates/categorie/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block body %}
    <h1>Categorie</h1>

    <table class="table">
        <tbody>
            {#<tr>
                <th>Id</th>
                <td>{{ categorie.id }}</td>
            </tr>#}
            <tr>
                <th>NomCategorie</th>
                <td>{{ categorie.nomCategorie }}</td>
            </tr>
            {# 
            <tr>
                <th>User_create</th>
                <td>{{ categorie.userCreate }}</td>
            </tr>
            <tr>
                <th>User_update</th>
                <td>{{ categorie.userUpdate }}</td>
            </tr>
            <tr>
                <th>User_delete</th>
                <td>{{ categorie.userDelete }}</td>
            </tr>
            <tr>
                <th>Date_create</th>
                <td>{{ categorie.dateCreate ? categorie.dateCreate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_update</th>
                <td>{{ categorie.dateUpdate ? categorie.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_delete</th>
                <td>{{ categorie.dateDelete ? categorie.dateDelete|date('Y-m-d H:i:s') : '' }}</td>
            </tr> 
            #}
        </tbody>
    </table>

    <a href="{{ path('app_categorie_index') }}" class="list-button">Liste Catégorie</a>
    <a href="{{ path('app_categorie_edit', {'id': categorie.id}) }}" class="list-button">Modifier</a>
    {{ include('categorie/_delete_form.html.twig') }}
{% endblock %}